<?php
// This file is generated by /vagrant/mediawiki/extensions/OOUIPlayground, do not adjust manually

global $wgAutoloadClasses;

$wgAutoloadClasses += array(
	'ConfiguredCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'GeSHICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'ICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'MultiCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'MultiGeSHICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'MultiPreCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'NullCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground' => __DIR__ . '/includes/Parser.php',
	'OOUIPlayground\\Templating' => __DIR__ . '/includes/Templating.php',
	'OOUIPlayground\\WidgetDocumenter' => __DIR__ . '/includes/WidgetDocumenter.php',
	'PreCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
);
