<?php
// This file is generated by /Users/andrew/wm-dev/vagrant/mediawiki/extensions/OOUIPlayground, do not adjust manually

global $wgAutoloadClasses;

$wgAutoloadClasses += array(
	'OOUIPlayground\\ArgumentFilterGroup' => __DIR__ . '/includes/argument-filters/ArgumentFilter.php',
	'OOUIPlayground\\ArgumentFilterInterface' => __DIR__ . '/includes/argument-filters/ArgumentFilter.php',
	'OOUIPlayground\\ConfiguredCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\GeSHICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\GroupElementFilter' => __DIR__ . '/includes/argument-filters/GroupElementFilter.php',
	'OOUIPlayground\\ICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\InvalidGroupElementItemException' => __DIR__ . '/includes/argument-filters/GroupElementFilter.php',
	'OOUIPlayground\\MockFilter' => __DIR__ . '/tests/phpunit/mocks/MockFilter.php',
	'OOUIPlayground\\MultiCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\MultiGeSHICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\MultiPreCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\NoSuchWidgetException' => __DIR__ . '/includes/WidgetInfo.php',
	'OOUIPlayground\\NoTypeGiven' => __DIR__ . '/includes/WidgetFactory.php',
	'OOUIPlayground\\NullCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\ParserHooks' => __DIR__ . '/includes/ParserHooks.php',
	'OOUIPlayground\\PreCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\WidgetDocumenter' => __DIR__ . '/includes/WidgetDocumenter.php',
	'OOUIPlayground\\WidgetFactory' => __DIR__ . '/includes/WidgetFactory.php',
	'OOUIPlayground\\WidgetInfo' => __DIR__ . '/includes/WidgetInfo.php',
	'OOUIPlayground\\WidgetRepository' => __DIR__ . '/includes/WidgetInfo.php',
	'OOUI\\MockGroupWidget' => __DIR__ . '/tests/phpunit/mocks/MockWidget.php',
	'OOUI\\MockWidget' => __DIR__ . '/tests/phpunit/mocks/MockWidget.php',
);
