<?php
// This file is generated by /vagrant/mediawiki/extensions/OOUIPlayground, do not adjust manually

global $wgAutoloadClasses;

$wgAutoloadClasses += array(
	'ArgumentFilterInterface' => __DIR__ . '/includes/argument-filters/ArgumentFilter.php',
	'GroupElementFilter' => __DIR__ . '/includes/argument-filters/GroupElementFilter.php',
	'OOUIPlayground\\ConfiguredCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\GeSHICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\ICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\MultiCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\MultiGeSHICodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\MultiPreCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\NullCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\ParserHooks' => __DIR__ . '/includes/ParserHooks.php',
	'OOUIPlayground\\PreCodeRenderer' => __DIR__ . '/includes/CodeRenderer.php',
	'OOUIPlayground\\Templating' => __DIR__ . '/includes/Templating.php',
	'OOUIPlayground\\WidgetDocumenter' => __DIR__ . '/includes/WidgetDocumenter.php',
	'OOUIPlayground\\WidgetInfo' => __DIR__ . '/includes/WidgetInfo.php',
	'OOUIPlayground\\WidgetRepository' => __DIR__ . '/includes/WidgetInfo.php',
);
